-- Seed data for WritingCriteriaTemplate
-- This file is executed after Django migrations in entrypoint.sh

INSERT INTO writing_criteria_template (level, band, content, communicative_achievement, organisation, language)
VALUES
-- A2 Level
('A2', 0, 'Content is totally irrelevant. Target reader is not informed.', '', 'Performance below Band 1.', 'Performance below Band 1.'),
('A2', 1, 'Irrelevances and misinterpretation of task may be present. Target reader is minimally informed.', '', 'Production unlikely to be connected, though punctuation and simple connectors (i.e. ''and'') may on occasion be used.', 'Produces basic vocabulary of isolated words and phrases. Produces few simple grammatical forms with only limited control.'),
('A2', 2, 'Performance shares features of Bands 1 and 3', '', 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3'),
('A2', 3, 'Minor irrelevances and/or omissions may be present. Target reader is on the whole informed.', '', 'Text is connected using basic, high-frequency linking words.', 'Uses basic vocabulary reasonably appropriately. Uses simple grammatical forms with some degree of control. Errors may impede meaning at times.'),
('A2', 4, 'Performance shares features of Bands 3 and 5', '', 'Performance shares features of Bands 3 and 5', 'Performance shares features of Bands 3 and 5'),
('A2', 5, 'All content is relevant to the task. Target reader is fully informed.', '', 'Text is connected and coherent, using basic linking words and a limited number of cohesive devices.', 'Uses everyday vocabulary generally appropriately, while occasionally overusing certain lexis. Uses simple grammatical forms with a good degree of control. While errors are noticeable, meaning can still be determined.'),
-- B1 Level
('B1', 0, 'Content is totally irrelevant. Target reader is not informed.', 'Performance below Band 1', 'Performance below Band 1', 'Performance below Band 1'),
('B1', 1, 'Irrelevances and misinterpretation of task may be present. Target reader is minimally informed', 'Produces text that communicates simple ideas in simple ways.', 'Text is connected using basic, high-frequency linking words', 'Uses basic vocabulary reasonably appropriately. Uses simple grammatical forms with some degree of control. Errors may impede meaning at times.'),
('B1', 2, 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3'),
('B1', 3, 'Minor irrelevances and/or omissions may be present. Target reader is on the whole informed.', 'Uses the conventions of the communicative task in generally appropriate ways to communicate straightforward ideas.', 'Text is connected and coherent, using basic linking words and a limited number of cohesive devices.', 'Uses everyday vocabulary generally appropriately, while occasionally overusing certain lexis. Uses simple grammatical forms with a good degree of control. While errors are noticeable, meaning can still be determined.'),
('B1', 4, 'Performance shares features of Bands 3 and 5.', 'Performance shares features of Bands 3 and 5.', 'Performance shares features of Bands 3 and 5.', 'Performance shares features of Bands 3 and 5.'),
('B1', 5, 'All content is relevant to the task. Target reader is fully informed', 'Uses the conventions of the communicative task to hold the target reader''s attention and communicate straightforward ideas.', 'Text is generally well organised and coherent, using a variety of linking words and cohesive devices.', 'Uses a range of everyday vocabulary appropriately, with occasional inappropriate use of less common lexis. Uses a range of simple and some complex grammatical forms with a good degree of control. Errors do not impede communication'),
-- B2 Level
('B2', 0, 'Content is totally irrelevant. Target reader is not informed.', 'Performance below Band 1.', 'Performance below Band 1.', 'Performance below Band 1.'),
('B2', 1, 'Irrelevances and misinterpretation of task may be present. Target reader is minimally informed.', 'Uses the conventions of the communicative task in generally appropriate ways to communicate straightforward ideas.', 'Text is connected and coherent, using basic linking words and a limited number of cohesive devices.', 'Uses everyday vocabulary generally appropriately, while occasionally overusing certain lexis. Uses simple grammatical forms with a good degree of control. While errors are noticeable, meaning can still be determined.'),
('B2', 2, 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3', 'Performance shares features of Bands 1 and 3'),
('B2', 3, 'Minor irrelevances and/or omissions may be present. Target reader is on the whole informed.', 'Uses the conventions of the communicative task to hold the target reader''s attention and communicate straightforward ideas.', 'Text is generally well organised and coherent, using a variety of linking words and cohesive devices.', 'Uses a range of everyday vocabulary appropriately, with occasional inappropriate use of less common lexis. Uses a range of simple and some complex grammatical forms with a good degree of control. Errors do not impede'),
('B2', 4, 'Performance shares features of Bands 3 and 5.', 'Performance shares features of Bands 3 and 5.', 'Performance shares features of Bands 3 and 5.', 'Performance shares features of Bands 3 and 5.'),
('B2', 5, 'All content is relevant to the task. Target reader is fully informed.', 'Uses the conventions of the communicative task effectively to hold the target reader''s attention and communicate straightforward and complex ideas, as appropriate', 'Text is well organised and coherent, using a variety of cohesive devices and organisational patterns to generally good effect.', 'Uses a range of vocabulary, including less common lexis, appropriately. Uses a range of simple and complex grammatical forms with control and flexibility. Occasional errors may be present but do not impede communication.')
ON CONFLICT (level, band) DO NOTHING;
