services:
  backend:
    build: .
    container_name: english_app_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./nens-english-backend-sa.json:/app/nens-english-backend-sa.json:ro

  redis:
    image: redis:8.4
    container_name: english_app_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
