FROM minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1

# Copy initialization scripts
COPY init/minio.sh /minio.sh

# Set execute permissions for the script
RUN chmod +x /minio.sh

# Set the entrypoint to the initialization script
ENTRYPOINT ["/minio.sh"]