services:
  backend:
    build: .
    container_name: english_app_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./test-nens-english-app-sa-key.json:/app/test-nens-english-app-sa-key.json:ro

  redis:
    image: redis:8.4
    container_name: english_app_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
