# Generated by Django 5.2.7 on 2026-03-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfeedback',
            name='source',
        ),
        migrations.AddField(
            model_name='testfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testfeedback',
            name='created_by',
            field=models.CharField(choices=[('A', 'AI'), ('T', 'Teacher')], default='T', max_length=10),
        ),
    ]
