# Generated by Django 5.2.7 on 2026-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_testfeedback_source_testfeedback_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfeedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
