# Generated by Django 5.2.7 on 2026-03-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('test_histories', '0004_alter_productivetesthistory_ai_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productive_test_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='test_histories.productivetesthistory'),
        ),
    ]
