# Generated by Django 5.2.7 on 2026-05-24 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', '-created_at'], name='post_commen_post_id_29b25e_idx'),
        ),
    ]
