# Generated by Django 5.2.7 on 2026-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_productive_test_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
