# Generated by Django 5.2.7 on 2026-05-13 05:38

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('file_storage_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='users/avatars/default-avatar.jpg', null=True, upload_to='users/avatars/')),
                ('cover', models.ImageField(blank=True, default='users/covers/default-cover.jpg', null=True, upload_to='users/covers/')),
                ('status', models.CharField(choices=[('P', 'Pending Verification'), ('I', 'Incomplete Profile'), ('W', 'Waiting Approval'), ('V', 'Verified'), ('D', 'Disabled')], default='P', max_length=1)),
                ('role', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], default='S', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_workplace', models.CharField(max_length=255)),
                ('teacher_type', models.CharField(choices=[('S', 'School Teacher'), ('C', 'Center Teacher'), ('F', 'Freelance Teacher')], default='F', max_length=1)),
                ('experience_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('introduction', models.TextField()),
                ('credentials', models.JSONField(default=dict)),
                ('weekly_ai_turn', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cumulative_point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_ai_turn', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_ai_turn', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_test', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('qualified_test', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_submitted_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('streak_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='user_progress.userlevel')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
