# Generated by Django 5.2.7 on 2025-12-08 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_teacher_current_workplace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="experience_year",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
