# Generated by Django 5.2.7 on 2025-12-12 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teacher_experience_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file_storage_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
