# Generated by Django 5.2.7 on 2026-01-25 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_cover_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_storage_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
