# Generated by Django 5.2.7 on 2026-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='users/covers/default-cover.jpg', null=True, upload_to='users/covers/'),
        ),
    ]
