# Generated by Django 5.2.7 on 2026-03-04 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_file_storage_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='weekly_ai_turn',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
