# Generated by Django 5.2.7 on 2026-04-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teacher_weekly_ai_turn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_attempt_at',
            new_name='last_submitted_date',
        ),
    ]
