# Generated by Django 5.2.7 on 2026-02-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_user_file_storage_uuid'),
        ('tests', '0013_expbonusrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductiveTestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('audio_path', models.TextField(blank=True, null=True)),
                ('user_answer_text', models.TextField(blank=True, null=True)),
                ('user_note_text', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('earned_bonus_point', models.IntegerField(default=0)),
                ('productive_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tests.productivetest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productive_test_histories', to='accounts.student')),
            ],
            options={
                'db_table': 'productive_test_history',
                'unique_together': {('student', 'productive_test', 'attempt')},
            },
        ),
    ]
