# Generated by Django 5.2.7 on 2026-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_usernam_b79065_idx'),
        ('test_histories', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productivetesthistory',
            index=models.Index(fields=['productive_test', 'type'], name='productive__product_455b19_idx'),
        ),
        migrations.AddIndex(
            model_name='productivetesthistory',
            index=models.Index(fields=['student', 'type', '-start_time'], name='productive__student_0373b3_idx'),
        ),
        migrations.AddIndex(
            model_name='receptiveanswerhistory',
            index=models.Index(fields=['receptive_test_history', 'is_correct'], name='receptive_a_recepti_ba735b_idx'),
        ),
        migrations.AddIndex(
            model_name='receptivetesthistory',
            index=models.Index(fields=['receptive_test', 'type'], name='receptive_t_recepti_0353ab_idx'),
        ),
        migrations.AddIndex(
            model_name='receptivetesthistory',
            index=models.Index(fields=['student', 'type', '-start_time'], name='receptive_t_student_56b071_idx'),
        ),
    ]
