# Generated by Django 5.2.7 on 2026-02-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_file_storage_uuid'),
        ('test_histories', '0001_initial'),
        ('tests', '0013_expbonusrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productivetesthistory',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='productivetesthistory',
            name='type',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Submission')], default='D', max_length=1),
        ),
        migrations.AddIndex(
            model_name='productivetesthistory',
            index=models.Index(fields=['student', 'productive_test', 'attempt', 'type'], name='productive__student_0c1bfc_idx'),
        ),
    ]
