# Generated by Django 5.2.7 on 2026-02-25 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_file_storage_uuid'),
        ('test_histories', '0002_alter_productivetesthistory_options_and_more'),
        ('tests', '0013_expbonusrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptiveTestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('D', 'Draft'), ('S', 'Submission')], default='D', max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_bonus_point', models.IntegerField(default=0)),
                ('receptive_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tests.receptivetest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_test_histories', to='accounts.student')),
            ],
            options={
                'db_table': 'receptive_test_history',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReceptiveAnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, default=False, null=True)),
                ('receptive_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='tests.receptiveanswer')),
                ('receptive_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='tests.receptivequestion')),
                ('receptive_test_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='test_histories.receptivetesthistory')),
            ],
            options={
                'db_table': 'receptive_answer_history',
            },
        ),
        migrations.AddIndex(
            model_name='receptivetesthistory',
            index=models.Index(fields=['student', 'receptive_test', 'attempt', 'type'], name='receptive_t_student_1ceb87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receptivetesthistory',
            unique_together={('student', 'receptive_test', 'attempt')},
        ),
        migrations.AddIndex(
            model_name='receptiveanswerhistory',
            index=models.Index(fields=['receptive_test_history', 'receptive_question', 'receptive_answer'], name='receptive_a_recepti_a8fee5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receptiveanswerhistory',
            unique_together={('receptive_test_history', 'receptive_question')},
        ),
    ]
