# Generated by Django 5.2.7 on 2026-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_histories', '0003_receptivetesthistory_receptiveanswerhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivetesthistory',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
