# Generated by Django 5.2.7 on 2026-04-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_histories', '0004_alter_productivetesthistory_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptivetesthistory',
            name='bonus_point',
            field=models.IntegerField(default=0),
        ),
    ]
