# Generated by Django 5.2.7 on 2026-04-06 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_histories', '0005_receptivetesthistory_bonus_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptivetesthistory',
            name='bonus_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receptivetesthistory',
            name='earned_bonus_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
