# Generated by Django 5.2.7 on 2025-12-31 01:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_user_file_storage_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('A1', 'A1'), ('A2', 'A2')], default='A1', max_length=2)),
                ('skill', models.CharField(choices=[('R', 'Reading'), ('L', 'Listening'), ('S', 'Speaking'), ('W', 'Writing')], default='R', max_length=1)),
                ('time', models.IntegerField(help_text='Time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('completed_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('D', 'Draft'), ('I', 'In Review'), ('P', 'Published'), ('R', 'Removed')], default='D', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_created', to='accounts.teacher')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='ProductiveTest',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tests.test')),
                ('format', models.CharField(choices=[], max_length=1)),
                ('question_text', models.TextField()),
                ('resources', models.JSONField(default=dict)),
                ('criterias', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'productive_test',
            },
        ),
        migrations.CreateModel(
            name='ReceptiveTest',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tests.test')),
                ('total_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_qualified_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'receptive_test',
            },
        ),
    ]
