# Generated by Django 5.2.7 on 2026-05-13 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('R', 'Receptive test'), ('P', 'Productive test')], default='R', max_length=1)),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], default='A1', max_length=2)),
                ('skill', models.CharField(choices=[('R', 'Reading'), ('L', 'Listening'), ('S', 'Speaking'), ('W', 'Writing')], default='R', max_length=1)),
                ('time', models.IntegerField(help_text='Time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('D', 'Draft'), ('I', 'In Review'), ('P', 'Published'), ('R', 'Removed')], default='D', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_created', to='accounts.teacher')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='ReceptivePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('format', models.CharField(choices=[('A', 'Listening - Multiple Choice images'), ('B', 'Listening - Multiple Choice text (one audio per question)'), ('C', 'Listening - Multiple Choice text (one audio for all questions)'), ('D', 'Listening - Fill in the blanks'), ('E', 'Listening - Matching'), ('F', 'Reading - Multiple Choice (short text)'), ('G', 'Reading - Multiple Choice (long text)'), ('H', 'Reading - Fill in the blanks (multiple choice)'), ('I', 'Reading - Fill in the blanks (text)'), ('J', 'Reading - Matching')], max_length=1)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('resources', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'receptive_part',
            },
        ),
        migrations.CreateModel(
            name='ProductiveTest',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='productive_test', serialize=False, to='tests.test')),
                ('format', models.CharField(choices=[('A', 'Writing - Email'), ('B', 'Writing - Article'), ('C', 'Writing - Tell a story based on pictures'), ('D', 'Writing - Essay'), ('E', 'Writing - Letter'), ('F', 'Writing - Reviews'), ('G', 'Speaking - Narrative'), ('H', 'Speaking - Description'), ('I', 'Speaking - Social argument'), ('J', 'Speaking - Reading aloud')], max_length=1)),
                ('topic', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('min_word', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('glue_text', models.TextField(blank=True, null=True)),
                ('glue_resources', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'productive_test',
            },
        ),
        migrations.CreateModel(
            name='ReceptiveTest',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='receptive_test', serialize=False, to='tests.test')),
                ('total_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'receptive_test',
            },
        ),
        migrations.CreateModel(
            name='ReadingCriteriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('checkpoints', models.JSONField(default=list)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'reading_criteria_template',
                'constraints': [models.UniqueConstraint(fields=('level', 'code'), name='unique_reading_level_code')],
            },
        ),
        migrations.CreateModel(
            name='ReceptiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('resources', models.JSONField(default=dict)),
                ('receptive_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_questions', to='tests.receptivepart')),
            ],
            options={
                'db_table': 'receptive_question',
            },
        ),
        migrations.CreateModel(
            name='ReceptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(blank=True, max_length=1, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('resources', models.JSONField(default=dict)),
                ('receptive_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_answers', to='tests.receptivequestion')),
            ],
            options={
                'db_table': 'receptive_answer',
            },
        ),
        migrations.CreateModel(
            name='SpeakingCriteriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('band', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grammar_and_vocabulary', models.TextField(blank=True, null=True)),
                ('discourse_management', models.TextField(blank=True, null=True)),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('task_achievement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speaking_criteria_template',
                'constraints': [models.UniqueConstraint(fields=('level', 'band'), name='unique_speaking_level_band')],
            },
        ),
        migrations.CreateModel(
            name='WritingCriteriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('band', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField(blank=True, null=True)),
                ('communicative_achievement', models.TextField(blank=True, null=True)),
                ('organisation', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writing_criteria_template',
                'constraints': [models.UniqueConstraint(fields=('level', 'band'), name='unique_level_band')],
            },
        ),
        migrations.AddField(
            model_name='receptivepart',
            name='receptive_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_parts', to='tests.receptivetest'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('skill__in', ['R', 'L']), ('type', 'R')), models.Q(('skill__in', ['S', 'W']), ('type', 'P')), _connector='OR'), name='test_type_skill_compatibility'),
        ),
    ]
