# Generated by Django 5.2.7 on 2025-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivetest',
            name='criterias',
        ),
        migrations.AddField(
            model_name='productivetest',
            name='criteria',
            field=models.JSONField(default=dict),
        ),
    ]
