# Generated by Django 5.2.7 on 2026-01-02 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_productivetest_criterias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptivePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('format', models.CharField(choices=[('A', 'Listening - Multiple Choice images'), ('B', 'Listening - Multiple Choice text (one audio per question)'), ('C', 'Listening - Multiple Choice text (one audio for all questions)'), ('D', 'Listening - Fill in the blanks'), ('E', 'Listening - Matching'), ('F', 'Reading - Multiple Choice (short text)'), ('G', 'Reading - Multiple Choice (long text)'), ('H', 'Reading - Fill in the blanks (multiple choice)'), ('I', 'Reading - Fill in the blanks (text)'), ('J', 'Reading - Matching')], max_length=1)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('resources', models.JSONField(default=dict)),
                ('receptive_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_parts', to='tests.receptivetest')),
            ],
            options={
                'db_table': 'receptive_part',
            },
        ),
        migrations.CreateModel(
            name='ReceptiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('resources', models.JSONField(default=dict)),
                ('receptive_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_questions', to='tests.receptivepart')),
            ],
            options={
                'db_table': 'receptive_question',
            },
        ),
        migrations.CreateModel(
            name='ReceptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=1)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('resources', models.JSONField(default=dict)),
                ('receptive_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptive_answers', to='tests.receptivequestion')),
            ],
            options={
                'db_table': 'receptive_answer',
            },
        ),
    ]
