# Generated by Django 5.2.7 on 2026-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_receptivepart_receptivequestion_receptiveanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptiveanswer',
            name='option_label',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
