# Generated by Django 5.2.7 on 2026-01-10 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_user_alter_teacher_user'),
        ('tests', '0005_alter_receptiveanswer_option_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingCriteriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('band', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content', models.TextField(blank=True, null=True)),
                ('communicative_achievement', models.TextField(blank=True, null=True)),
                ('organisation', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writing_criteria_template',
            },
        ),
        migrations.RemoveField(
            model_name='productivetest',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='productivetest',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='productivetest',
            name='resources',
        ),
        migrations.AddField(
            model_name='productivetest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productivetest',
            name='glue_resources',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productivetest',
            name='glue_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productivetest',
            name='min_word',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productivetest',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('R', 'Receptive test'), ('P', 'Productive test')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='productivetest',
            name='format',
            field=models.CharField(choices=[('A', 'Writing - Email'), ('B', 'Writing - Article'), ('C', 'Writing - Tell a story based on pictures'), ('D', 'Writing - Essay'), ('E', 'Writing - Letter'), ('F', 'Writing - Reviews'), ('G', 'Speaking - Narrative'), ('H', 'Speaking - Description'), ('I', 'Speaking - Social argument'), ('J', 'Speaking - Reading aloud')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('skill__in', ['R', 'L']), ('type', 'R')), models.Q(('skill__in', ['S', 'W']), ('type', 'P')), _connector='OR'), name='test_type_skill_compatibility'),
        ),
    ]
