# Generated by Django 5.2.7 on 2026-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_writingcriteriatemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivetest',
            name='topic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='writingcriteriatemplate',
            constraint=models.UniqueConstraint(fields=('level', 'band'), name='unique_level_band'),
        ),
    ]
