# Generated by Django 5.2.7 on 2026-01-14 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_productivetest_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='completed_bonus',
        ),
        migrations.CreateModel(
            name='CompletedBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('R', 'Reading'), ('L', 'Listening'), ('S', 'Speaking'), ('W', 'Writing')], max_length=1)),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('bonus_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'completed_bonus',
                'constraints': [models.UniqueConstraint(fields=('skill', 'level'), name='unique_skill_level')],
            },
        ),
    ]
