# Generated by Django 5.2.7 on 2026-01-14 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_remove_test_completed_bonus_completedbonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedbonus',
            name='bonus_points',
        ),
        migrations.AddField(
            model_name='completedbonus',
            name='completed_bonus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
