# Generated by Django 5.2.7 on 2026-01-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_remove_completedbonus_bonus_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptivetest',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='receptive_test', serialize=False, to='tests.test'),
        ),
    ]
