# Generated by Django 5.2.7 on 2026-01-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_receptivetest_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivetest',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='productive_test', serialize=False, to='tests.test'),
        ),
    ]
