# Generated by Django 5.2.7 on 2026-01-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_productivetest_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptivetest',
            name='base_qualified_bonus',
        ),
    ]
