# Generated by Django 5.2.7 on 2026-02-03 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_receptivetest_base_qualified_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXPBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.FloatField(help_text='Minimum required percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_percentage', models.FloatField(help_text='Maximum percentage achievable', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('exp_percentage', models.FloatField(help_text='EXP percentage awarded', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rating', models.TextField()),
                ('feedback_message', models.TextField()),
            ],
            options={
                'db_table': 'exp_bonus_rule',
            },
        ),
    ]
