# Generated by Django 5.2.7 on 2026-03-03 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_expbonusrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingCriteriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('band', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grammar_and_vocabulary', models.TextField(blank=True, null=True)),
                ('discourse_management', models.TextField(blank=True, null=True)),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('interactive_communication', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speaking_criteria_template',
                'constraints': [models.UniqueConstraint(fields=('level', 'band'), name='unique_speaking_level_band')],
            },
        ),
    ]
