# Generated by Django 5.2.7 on 2026-03-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_speakingcriteriatemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingcriteriatemplate',
            name='interactive_communication',
        ),
        migrations.AddField(
            model_name='speakingcriteriatemplate',
            name='task_achievement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
