# Generated by Django 5.2.7 on 2026-03-22 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_remove_speakingcriteriatemplate_interactive_communication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingCriteriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('checkpoints', models.JSONField(default=list)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'reading_criteria_template',
                'constraints': [models.UniqueConstraint(fields=('level', 'code'), name='unique_reading_level_code')],
            },
        ),
    ]
