# Generated by Django 5.2.7 on 2026-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_readingcriteriatemplate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expbonusrule',
            constraint=models.UniqueConstraint(fields=('min_percentage', 'max_percentage'), name='unique_exp_bonus_rule_range'),
        ),
    ]
