# Generated by Django 5.2.7 on 2026-04-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_expbonusrule_unique_exp_bonus_rule_range'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedBonus',
        ),
        migrations.DeleteModel(
            name='EXPBonusRule',
        ),
    ]
