# Generated by Django 5.2.7 on 2026-04-28 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=120)),
                ('is_title_auto', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('translate', 'Translate'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('brainstorm', 'Brainstorm'), ('general', 'General')], default='general', max_length=20)),
                ('target_skill', models.CharField(choices=[('R', 'Reading'), ('W', 'Writing'), ('S', 'Speaking'), ('L', 'Listening'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
                ('level', models.CharField(blank=True, max_length=32, null=True)),
                ('system_prompt_version', models.CharField(default='v1', max_length=32)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_conversation',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=12)),
                ('content', models.TextField()),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=120, null=True)),
                ('token_usage_prompt', models.PositiveIntegerField(blank=True, null=True)),
                ('token_usage_completion', models.PositiveIntegerField(blank=True, null=True)),
                ('token_usage_total', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'db_table': 'assistant_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(default=50)),
                ('used', models.PositiveIntegerField(default=0)),
                ('period_seconds', models.PositiveIntegerField(default=86400)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_quota',
            },
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', 'last_message_at'], name='assistant_c_user_id_127dea_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', 'is_archived'], name='assistant_c_user_id_314c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_m_convers_dbe832_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['status'], name='assistant_m_status_6e88ea_idx'),
        ),
    ]
