# Generated by Django 5.2.7 on 2026-05-24 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', 'is_archived', 'last_message_at'], name='assistant_c_user_id_07f283_idx'),
        ),
    ]
