# Generated by Django 5.2.7 on 2026-04-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantconversation',
            name='target_skill',
        ),
    ]
