# Generated by Django 5.2.7 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_assistantconversation_target_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantquota',
            name='period_seconds',
            field=models.PositiveIntegerField(default=43200),
        ),
    ]
