# Generated by Django 5.2.7 on 2026-04-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_assistantquota_period_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantmessage',
            name='content_json',
        ),
        migrations.RemoveField(
            model_name='assistantmessage',
            name='model_name',
        ),
    ]
