# Generated by Django 5.2.7 on 2026-05-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_remove_assistantmessage_content_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='mode',
            field=models.CharField(blank=True, choices=[('translate', 'Translate'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('brainstorm', 'Brainstorm'), ('general', 'General')], max_length=20, null=True),
        ),
    ]
