# Generated by Django 5.2.7 on 2026-05-08 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_day', models.IntegerField(help_text='Required streak day to unlock this reward', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_reward', models.IntegerField(default=0, help_text='XP awarded when user reaches streak_day', validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_turn_reward', models.IntegerField(default=0, help_text='Total AI turns shown in reward config', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'streak_reward_rule',
                'ordering': ['streak_day'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_title', models.CharField(max_length=50)),
                ('level_icon', models.URLField(blank=True, null=True)),
                ('min_xp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_xp', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'user_level',
                'ordering': ['min_xp'],
            },
        ),
        migrations.CreateModel(
            name='CompletedBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('R', 'Reading'), ('L', 'Listening'), ('S', 'Speaking'), ('W', 'Writing')], max_length=1)),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('completed_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'completed_bonus',
                'constraints': [models.UniqueConstraint(fields=('skill', 'level'), name='unique_skill_level')],
            },
        ),
        migrations.CreateModel(
            name='EXPBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.FloatField(help_text='Minimum required percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_percentage', models.FloatField(help_text='Maximum percentage achievable', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('exp_percentage', models.FloatField(help_text='EXP percentage awarded', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rating', models.TextField()),
                ('feedback_message', models.TextField()),
            ],
            options={
                'db_table': 'exp_bonus_rule',
                'constraints': [models.UniqueConstraint(fields=('min_percentage', 'max_percentage'), name='unique_exp_bonus_rule_range')],
            },
        ),
    ]
