# Generated by Django 5.2.7 on 2026-04-14 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('R', 'Reading'), ('L', 'Listening'), ('S', 'Speaking'), ('W', 'Writing')], max_length=1)),
                ('level', models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('A1', 'A1'), ('A2', 'A2')], max_length=2)),
                ('completed_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'completed_bonus',
                'constraints': [models.UniqueConstraint(fields=('skill', 'level'), name='unique_skill_level')],
            },
        ),
        migrations.CreateModel(
            name='EXPBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.FloatField(help_text='Minimum required percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_percentage', models.FloatField(help_text='Maximum percentage achievable', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('exp_percentage', models.FloatField(help_text='EXP percentage awarded', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('rating', models.TextField()),
                ('feedback_message', models.TextField()),
            ],
            options={
                'db_table': 'exp_bonus_rule',
                'constraints': [models.UniqueConstraint(fields=('min_percentage', 'max_percentage'), name='unique_exp_bonus_rule_range')],
            },
        ),
    ]
