# Generated by Django 5.2.7 on 2026-04-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0002_completedbonus_expbonusrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_day', models.IntegerField(help_text='Required streak day to unlock this reward', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_reward', models.IntegerField(default=0, help_text='XP awarded when user reaches streak_day', validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_turn_reward', models.IntegerField(default=0, help_text='Total AI turns shown in reward config', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'streak_reward_rule',
                'ordering': ['streak_day'],
            },
        ),
    ]
